# Site settings
title: 18F Consulting
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/navy-reserve"
url: "https://18f.github.io/navy-reserve"

# Header
header:
  logo_text: 18F Consulting
  logo_img: logo.svg
  # nav:
  #   - text: Article
  #     link: /example-article
  #   - text: About
  #     link: /about
  #   - text: Blog
  #     link: /blog

# Edit pages
edit_page:
  # enabled: true  # Enabled by default for pages and posts
  text: "Edit this page »"
  github:
    author: 18F
    repo:   navy-reserve
    branch: gh-pages

# Posts
posts_path: /blog
permalink: "/blog/:year/:month/:day/:title"

# Pagination
paginate: 5
paginate_path: "/blog/page:num"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: [hard_wrap, tables]

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: template/page
  - scope:
      path: ""
      type: posts
    values:
      layout: template/post
